routes:
/:
    controller: channel
    filter: tag:[design,product,animation]

collections:
  /:
    permalink: /{slug}/
    template: index

  /design/:
    permalink: /design/{slug}/
    template: design
    filter: primary_tag:design

  /product/:
    permalink: /product/{slug}/
    template: product
    filter: primary_tag:product

  /animation/:
    permalink: /animation/{slug}/
    template: animation
    filter: primary_tag:animation

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
